name: SonarCloud SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud_scan:
    name: SonarCloud SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip -q sonar-scanner-cli.zip
          export PATH="$PATH:$PWD/sonar-scanner-4.6.0.2311-linux/bin"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run SonarCloud Scan
        run: |
            -Dsonar.projectKey=sonaranalysis-agbii_emmanuel \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
