name: SonarCloud SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud_scan:
    name: SonarCloud SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Build with Maven and Run SonarCloud Scan
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=sonaranalysis-agbii_emmanuel \
            -Dsonar.organization=sonaranalysis-agbii \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
